# -*- coding: utf-8 -*-
"""Insurance data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jBG9i2T2q5xPkIJL1EcNBbS_5bMhLxt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

df = pd.read_csv('/content/insurance.csv')
print(df)

print(df.shape)

print(df.info())

##Cheacking Missing Values
df.isna().sum()

## relationship between the feature and target column using a count plot of categorical columns and a scatter plot of numerical columns
fig,axs =plt.subplots(1,3,sharey=True)
df.plot(kind='scatter',x='age',y='charges',ax=axs[0],figsize=(16,8))
df.plot(kind='scatter',x='children',y='charges',ax=axs[1])
df.plot(kind='scatter',x='bmi',y='charges',ax=axs[2])

sns.countplot(x='sex', data=df)
plt.title("Count of Male and Female")
plt.show()

sns.countplot(x='smoker', data=df)
plt.title("Count of Smokers and Non-Smokers")
plt.show()

sns.countplot(x='region', data=df)
plt.title("Count by Region")
plt.show()

sns.countplot(x='children', data=df)
plt.title("Count of Number of Children")
plt.show()

##box plot
sns.boxplot(x='sex', y='charges', data=df)
plt.title("Sex vs Charges")
plt.show()

sns.boxplot(x='smoker', y='charges', data=df)
plt.title("Smoker vs Charges")
plt.show()

sns.boxplot(x='region', y='charges', data=df)
plt.title("Region vs Charges")
plt.show()

##pair plot
sns.pairplot(df, hue='smoker')
plt.show()

##correlation heat map
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

##Age vs charges for smokers and non-smokers
sns.scatterplot(x='age', y='charges', hue='smoker', data=df)
plt.title("Age vs Charges for Smokers and Non-Smokers")
plt.show()

##Average charges by age and smoker status
avg_charges = df.groupby(['age', 'smoker'])['charges'].mean().reset_index()

sns.lineplot(x='age', y='charges', hue='smoker', data=avg_charges, marker='o')
plt.title("Average Charges by Age for Smokers and Non-Smokers")
plt.show()